// <auto-generated />
using Leave_Management_System.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Leave_Management_System.Migrations
{
    [DbContext(typeof(LeaveDbContext))]
    [Migration("20210112051619_leaveClass")]
    partial class leaveClass
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Leave_Management_System.Models.Class.Dean", b =>
                {
                    b.Property<int>("Dean_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("Dean_id");

                    b.ToTable("Dean");
                });

            modelBuilder.Entity("Leave_Management_System.Models.Class.Faculty", b =>
                {
                    b.Property<int>("Faculty_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("Faculty_id");

                    b.ToTable("Faculty");
                });

            modelBuilder.Entity("Leave_Management_System.Models.Class.LeaveHistory", b =>
                {
                    b.Property<int>("leave_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("leave_id");

                    b.ToTable("LeaveHistory");
                });

            modelBuilder.Entity("Leave_Management_System.Models.Class.Registrar", b =>
                {
                    b.Property<int>("Registrar_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("Registrar_id");

                    b.ToTable("Registrar");
                });

            modelBuilder.Entity("Leave_Management_System.Models.HOD", b =>
                {
                    b.Property<int>("HOD_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("HOD_id");

                    b.ToTable("HOD");
                });
#pragma warning restore 612, 618
        }
    }
}
